# Generated by Django 5.2.12 on 2026-04-30 21:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Calculation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "user_identifier",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("backup_hours", models.FloatField(default=5)),
                (
                    "system_voltage",
                    models.IntegerField(
                        choices=[(12, "12V"), (24, "24V"), (48, "48V")], default=12
                    ),
                ),
                ("sunlight_hours", models.FloatField(default=5)),
                ("total_load_watts", models.FloatField(blank=True, null=True)),
                ("adjusted_load_watts", models.FloatField(blank=True, null=True)),
                ("daily_energy_wh", models.FloatField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="CalculationAppliance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("quantity", models.PositiveIntegerField()),
                ("watts", models.FloatField()),
                ("hours_per_day", models.FloatField()),
                (
                    "calculation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="appliances",
                        to="calculations.calculation",
                    ),
                ),
            ],
        ),
    ]
