# Generated by Django 5.2.12 on 2026-04-30 21:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("calculations", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Recommendation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("inverter_kva", models.FloatField()),
                ("inverter_note", models.CharField(max_length=255)),
                ("battery_capacity_ah", models.FloatField()),
                ("battery_recommendation", models.CharField(max_length=255)),
                ("solar_total_watts", models.FloatField()),
                ("panel_size_watts", models.IntegerField(default=200)),
                ("panel_quantity", models.IntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "calculation",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recommendation",
                        to="calculations.calculation",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RecommendationTier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tier",
                    models.CharField(
                        choices=[
                            ("budget", "Budget"),
                            ("standard", "Standard"),
                            ("premium", "Premium"),
                        ],
                        max_length=20,
                    ),
                ),
                ("inverter", models.CharField(max_length=50)),
                ("battery", models.CharField(max_length=50)),
                ("solar_panels", models.CharField(max_length=50)),
                (
                    "estimated_cost",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "recommendation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tiers",
                        to="recommendations.recommendation",
                    ),
                ),
            ],
        ),
    ]
